"""The contract every Tango access goes through.

Only coroutines are exposed: there is no synchronous entry point to call from
the GUI thread by accident. Implementations guarantee that event callbacks run
on the caller's event loop, never on a transport thread.
"""

from collections.abc import Callable, Mapping, Sequence
from typing import Any, Protocol

from milonga.core.enums import EventType, LogLevel, PollableKind
from milonga.core.model import (
    AttributePropertyMap,
    AttributeSpec,
    AttributeValue,
    CommandSpec,
    DeviceInfo,
    DeviceRegistration,
    DeviceStateInfo,
    DeviceVersionInfo,
    EventData,
    LoggingTarget,
    PollingEntry,
    PropertyEntry,
    PropertyHistoryEntry,
    PropertyValues,
    ServerInfo,
)
from milonga.core.names import AttributeRef, DeviceName, ServerName

type SubscriptionId = int
type EventCallback = Callable[[EventData], None]


class DatabaseBackend(Protocol):
    """Everything Jive does to the Tango database."""

    # -- hosts and servers
    async def get_host_list(self, pattern: str = "*") -> tuple[str, ...]: ...
    async def get_host_server_list(self, host: str) -> tuple[ServerName, ...]: ...
    async def get_server_list(self, pattern: str = "*") -> tuple[ServerName, ...]: ...
    async def get_server_info(self, server: ServerName) -> ServerInfo: ...
    async def put_server_info(self, info: ServerInfo) -> None: ...
    async def get_server_class_list(self, server: ServerName) -> tuple[str, ...]: ...
    async def add_server(
        self, server: ServerName, devices: Sequence[DeviceRegistration]
    ) -> None: ...
    async def delete_server(self, server: ServerName) -> None: ...
    async def rename_server(self, old: ServerName, new: ServerName) -> None: ...

    # -- devices
    async def get_device_domain_list(self, pattern: str = "*") -> tuple[str, ...]: ...
    async def get_device_family_list(self, domain: str) -> tuple[str, ...]: ...
    async def get_device_member_list(self, domain: str, family: str) -> tuple[str, ...]: ...
    async def get_device_list(self, pattern: str = "*/*/*") -> tuple[DeviceName, ...]: ...
    async def get_device_list_for_class(self, class_name: str) -> tuple[DeviceName, ...]: ...
    async def get_device_list_for_server(self, server: ServerName) -> tuple[DeviceName, ...]: ...
    async def get_device_info(self, device: DeviceName) -> DeviceInfo: ...
    async def add_device(self, registration: DeviceRegistration) -> None: ...
    async def delete_device(self, device: DeviceName) -> None: ...
    async def rename_device(self, old: DeviceName, new: DeviceName) -> None: ...
    async def unexport_device(self, device: DeviceName) -> None: ...
    async def get_class_list(self, pattern: str = "*") -> tuple[str, ...]: ...

    # -- aliases
    async def get_device_alias_list(self, pattern: str = "*") -> tuple[str, ...]: ...
    async def get_alias_from_device(self, device: DeviceName) -> str | None: ...
    async def get_device_from_alias(self, alias: str) -> DeviceName: ...
    async def put_device_alias(self, device: DeviceName, alias: str) -> None: ...
    async def delete_device_alias(self, alias: str) -> None: ...

    # -- device properties
    async def get_device_property_names(self, device: DeviceName) -> tuple[str, ...]: ...
    async def get_device_properties(
        self, device: DeviceName, names: Sequence[str] | None = None
    ) -> tuple[PropertyEntry, ...]: ...
    async def put_device_properties(
        self, device: DeviceName, entries: Sequence[PropertyEntry]
    ) -> None: ...
    async def delete_device_properties(self, device: DeviceName, names: Sequence[str]) -> None: ...
    async def get_device_property_history(
        self, device: DeviceName, name: str
    ) -> tuple[PropertyHistoryEntry, ...]: ...

    # -- class properties
    async def get_class_property_names(self, class_name: str) -> tuple[str, ...]: ...
    async def get_class_properties(
        self, class_name: str, names: Sequence[str] | None = None
    ) -> tuple[PropertyEntry, ...]: ...
    async def put_class_properties(
        self, class_name: str, entries: Sequence[PropertyEntry]
    ) -> None: ...
    async def delete_class_properties(self, class_name: str, names: Sequence[str]) -> None: ...
    async def get_class_property_history(
        self, class_name: str, name: str
    ) -> tuple[PropertyHistoryEntry, ...]: ...

    # -- attribute properties
    async def get_device_attribute_properties(self, device: DeviceName) -> AttributePropertyMap: ...
    async def put_device_attribute_properties(
        self, device: DeviceName, properties: AttributePropertyMap
    ) -> None: ...
    async def delete_device_attribute_properties(
        self, device: DeviceName, attribute: str, names: Sequence[str]
    ) -> None: ...
    async def get_class_attribute_properties(self, class_name: str) -> AttributePropertyMap: ...
    async def put_class_attribute_properties(
        self, class_name: str, properties: AttributePropertyMap
    ) -> None: ...

    # -- free properties
    async def get_object_list(self, pattern: str = "*") -> tuple[str, ...]: ...
    async def get_object_property_names(self, obj: str) -> tuple[str, ...]: ...
    async def get_properties(
        self, obj: str, names: Sequence[str] | None = None
    ) -> tuple[PropertyEntry, ...]: ...
    async def put_properties(self, obj: str, entries: Sequence[PropertyEntry]) -> None: ...
    async def delete_properties(self, obj: str, names: Sequence[str]) -> None: ...
    async def get_property_history(
        self, obj: str, name: str
    ) -> tuple[PropertyHistoryEntry, ...]: ...

    # -- search
    async def find_devices_by_property(
        self, name: str, value: str | None = None
    ) -> tuple[DeviceName, ...]: ...


class DeviceBackend(Protocol):
    """Everything the device panel and the Starter client need from a live device."""

    async def ping(self, device: DeviceName) -> float: ...
    async def get_device_state(self, device: DeviceName) -> DeviceStateInfo: ...
    async def get_device_version(self, device: DeviceName) -> DeviceVersionInfo: ...

    async def get_attribute_specs(self, device: DeviceName) -> tuple[AttributeSpec, ...]: ...
    async def set_attribute_specs(
        self, device: DeviceName, specs: Sequence[AttributeSpec]
    ) -> None: ...
    async def read_attributes(
        self, device: DeviceName, names: Sequence[str]
    ) -> tuple[AttributeValue, ...]: ...
    async def write_attribute(self, device: DeviceName, name: str, value: Any) -> None: ...

    async def get_command_specs(self, device: DeviceName) -> tuple[CommandSpec, ...]: ...
    async def execute_command(self, device: DeviceName, command: str, argin: Any = None) -> Any: ...

    async def get_polling(self, device: DeviceName) -> tuple[PollingEntry, ...]: ...
    async def set_polling(
        self, device: DeviceName, name: str, kind: PollableKind, period_ms: int
    ) -> None: ...
    async def stop_polling(self, device: DeviceName, name: str, kind: PollableKind) -> None: ...

    async def get_logging_targets(self, device: DeviceName) -> tuple[LoggingTarget, ...]: ...
    async def add_logging_target(self, device: DeviceName, target: LoggingTarget) -> None: ...
    async def remove_logging_target(self, device: DeviceName, target: LoggingTarget) -> None: ...
    async def get_logging_level(self, device: DeviceName) -> LogLevel: ...
    async def set_logging_level(self, device: DeviceName, level: LogLevel) -> None: ...


class EventBackend(Protocol):
    """Push notification. Subscription failure is reported by raising."""

    async def subscribe_event(
        self, ref: AttributeRef, event_type: EventType, callback: EventCallback
    ) -> SubscriptionId: ...
    async def unsubscribe_event(self, subscription: SubscriptionId) -> None: ...


class TangoBackend(DatabaseBackend, DeviceBackend, EventBackend, Protocol):
    """A connection to one control system."""

    @property
    def tango_host(self) -> str: ...

    @property
    def writable(self) -> bool: ...

    async def close(self) -> None: ...


type PropertyMapping = Mapping[str, PropertyValues]
